name: build and deploy production

on:
  push:
    tags:
      - '*'

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Build image and push to GHCR
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: vue-app-006
          registry: ghcr.io
          username: natsuda006   # 👈 lowercase เท่านั้น
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ github.ref_name }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest

    env:
      CONTAINER_NAME: vue-app-006
      DOCKER_IMAGE_URL: ghcr.io/natsuda006/vue-app-006:${{ github.ref_name }}

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 167.172.92.228
          username: root
          password: ${{ secrets.DO_SECRET }}
          port: 22
          script: |
            docker logout ghcr.io || true
            docker login ghcr.io -u natsuda006 -p ${{ secrets.GITHUB_TOKEN }}

            docker rm -f vue-app-006 || true
            docker pull ghcr.io/natsuda006/vue-app-006:${{ github.ref_name }}

            docker run -d \
              --name vue-app-006 \
              --restart=always \
              -p 9777:80 \
              ghcr.io/natsuda006/vue-app-006:${{ github.ref_name }}